version: 2.1

working_directory: /tmp/cci-mps

executors:
  principal-executor:
    docker:
      - image: circleci/node:10

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  slack: circleci/slack@3.4.1

jobs:
  release:
    executor: principal-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run bump-version
      - run: |
            export RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^[0-9]' | tail -1) >> $BASH_ENV
            echo $RELEASE_VERSION
  start-notify:
    executor: principal-executor
    steps:
      - slack/notify:
          color: '#0000FF'
          mentions: 'channel'
          message: We just start a new building!
          webhook: ${SLACK_WEBHOOK}
      
workflows:
  build_and_push_image:
    jobs:
      - start-notify
      - release
      - aws-ecr/build-and-push-image:
          requires: 
            - release
          repo: inteloob/mps
          tag: 'latest'
          create-repo: true
          filters:
            branches:
                only:
                  - master
      - aws-ecr/build-and-push-image:
          requires: 
            - release
          repo: inteloob/volteomps
          tag: 'latest'
          create-repo: true
          filters:
            branches:
              only:
                - volteoMPS
      - aws-ecr/build-and-push-image:
          requires: 
            - release
          repo: inteloob/volteotest
          tag: "latest,${RELEASE_VERSION}"
          create-repo: true
          filters:
            branches:
              only:
                - volteoTest
