version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

jobs:
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run bump-version
      - run: |
            RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^[0-9]' | tail -1)
            echo $RELEASE_VERSION
  start-notify:
    executor: principal-executor
    steps:
      - slack/notify:
          color: '#0000FF'
          mentions: 'channel'
          message: We just start a new building!
          webhook: ${SLACK_WEBHOOK}
  end-notify:
    executor: principal-executor
    steps:
      - slack/notify:
          color: '#228B22'
          mentions: 'channel'
          title: Job completed.
          message: Success deploy!
          include_visit_job_action: false
          include_job_number_field: false
          webhook: ${SLACK_WEBHOOK}

workflows:
  build_and_push_image:
    jobs:
      - start-notify
      - release
      - aws-ecr/build-and-push-image_master:
          requires: 
            - release
          repo: inteloob/mps
          tag: 'latest'
          create-repo: true
          filters:
            branches:
                only:
                  - master
      - end-notify:
          requires: 
            - aws-ecr/build-and-push-image_master
      - aws-ecr/build-and-push-image_volteo:
          requires: 
            - release
          repo: inteloob/volteomps
          tag: 'latest'
          create-repo: true
          filters:
            branches:
              only:
                - volteoMPS
      - end-notify:
          requires: 
            - aws-ecr/build-and-push-image_volteo
      - aws-ecr/build-and-push-image_test:
          requires: 
            - release
          repo: inteloob/volteoTest
          tag: 'latest,${RELEASE_VERSION}'
          create-repo: true
          filters:
            branches:
              only:
                - volteoTEST
      - end-notify:
          requires: 
            - aws-ecr/build-and-push-image_test